# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: challenge2/my_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'challenge2/my_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x63hallenge2/my_service.proto\"\x19\n\tMyRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nMyResponse\x12\x0f\n\x07message\x18\x01 \x01(\t25\n\tMyService\x12(\n\x0bHelloServer\x12\n.MyRequest\x1a\x0b.MyResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'challenge2.my_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MYREQUEST']._serialized_start=31
  _globals['_MYREQUEST']._serialized_end=56
  _globals['_MYRESPONSE']._serialized_start=58
  _globals['_MYRESPONSE']._serialized_end=87
  _globals['_MYSERVICE']._serialized_start=89
  _globals['_MYSERVICE']._serialized_end=142
# @@protoc_insertion_point(module_scope)
